---
title: "STAT301 Worksheet3"
author: "Charles Sandahl"
date: "2026-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```


# Question 1
```{r}
eyeFlicker = c(26.8,27.9,23,25,26,24.8,25.7,24.5,
           26.4,24.2,28,26.9,29.1,
           25.7,27.2,29.9,28.5,29.4,29.4)
eyeColor = rep(c("brown", "green", "blue"), c(8, 5, 6))

eyeDF = data.frame(eyeColor, eyeFlicker)

eyeANOVA = aov(eyeFlicker ~ eyeColor, data = eyeDF)
summary(eyeANOVA)

TukeyHSD(eyeANOVA)

eyeDF %>%
  group_by(eyeColor) %>%
  summarise(avgFlicker = mean(eyeFlicker),
            eyeSE = sd(eyeFlicker)/sqrt(length(eyeFlicker)),
            tStar = qt(1-0.05/2, length(eyeFlicker)-1)) %>%
  ggplot(aes(x = eyeColor, y = avgFlicker)) + geom_point() +geom_errorbar(aes(ymin = avgFlicker - eyeSE * tStar,ymax = avgFlicker + eyeSE * tStar ))
```

# Question 2
```{r}
memoryActivityData = read_excel("Downloads/James Intrusive Memories Activity.xlsx")

memoryZeroANOVA = aov(Day_Zero_Number_of_Intrusions ~ Condition,
                      data = memoryActivityData)
summary(memoryZeroANOVA)

memorySevenANOVA = aov(memoryActivityData$Days_One_to_Seven_Number_of_Intrusions ~ memoryActivityData$Condition)
summary(memorySevenANOVA)

TukeyHSD(memorySevenANOVA)
```


