---
title: "Worksheet5"
author: "Charles Sandahl"
date: "2026-02-13"
output: html_document
---

```{r}
library(nlme)
library(readxl)
library(tidyverse)
library(multcomp)
```


# Question 1
```{r}
individual = rep(c(1:9), 3)
faces = as.factor(rep(c("alone", "different", "similar"), each = 9))
attractiveness = c(56.3,49.8,47.1,38.9,44.7,45.2,36.8,53.8,45.1,
                   55.9,49.7,52.5,41.6,47.0,43.9,37.3,52.7,46.2,
                   54.3,51.2,53.2,42.1,50.5,46.2,38.8,53.9,49.1)
faceData = data.frame(individual, faces, attractiveness)

faceANOVA = lme(attractiveness ~ faces, random = ~1|individual, data = faceData)
anova(faceANOVA)

facePostHoc = glht(faceANOVA, linfct = mcp(faces="Tukey"))
summary(facePostHoc)
```

# Question 2
```{r}
ID = rep(c(1:10), 6)
timeOfDay = as.factor(rep(c("Morning", "Afternoon"), each = 30))
cupSize = as.factor(rep(rep(c("8oz", "12oz", "16oz"), each = 10), 2))
cupsConsumed = c(1,1,0,1,2,0,1,1,1,1,
                 1,1,0,0,1,2,1,0,1,1,
                 0,1,1,0,1,1,0,0,1,0,
                 1,1,0,0,1,1,0,1,1,1,
                 0,1,0,0,1,0,0,0,1,0,
                 0,0,0,0,0,0,0,0,1,0)
coffeeData = data.frame(ID, timeOfDay, cupSize, cupsConsumed)

coffeeANOVA = lme(cupsConsumed ~ timeOfDay + cupSize + timeOfDay * cupSize,
                  random = ~1 | ID,
                  data = coffeeData)
anova(coffeeANOVA)
```

